In [18]:
import pandas as pd
import numpy as np

# save filepath to variable for easier access
# melbourne_file_path = '../input/melbourne-housing-snapshot/melb_data.csv'
# read the data and store data in DataFrame titled melbourne_data
melbourne_data = pd.read_csv("data/PreciosCasas/train.csv") 
# print a summary of the data in Melbourne data
print(melbourne_data.describe())

                Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726   
std       1.112799    30.202904     20.645407   181.066207   456.098091   
min       1.000

In [2]:
#Vamos a ver que variables elegimos
print(melbourne_data.columns)

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [3]:
#Queremos prededir el precio, será nuestro target, y cogeremos unas variables como pedictores 
y= melbourne_data.SalePrice
print(y.head())
melbourne_predictors = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X = melbourne_data[melbourne_predictors]
X.describe()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64


LotArea    YearBuilt     1stFlrSF     2ndFlrSF     FullBath  \
count    1460.000000  1460.000000  1460.000000  1460.000000  1460.000000   
mean    10516.828082  1971.267808  1162.626712   346.992466     1.565068   
std      9981.264932    30.202904   386.587738   436.528436     0.550916   
min      1300.000000  1872.000000   334.000000     0.000000     0.000000   
25%      7553.500000  1954.000000   882.000000     0.000000     1.000000   
50%      9478.500000  1973.000000  1087.000000     0.000000     2.000000   
75%     11601.500000  2000.000000  1391.250000   728.000000     2.000000   
max    215245.000000  2010.000000  4692.000000  2065.000000     3.000000   

       BedroomAbvGr  TotRmsAbvGrd  
count   1460.000000   1460.000000  
mean       2.866438      6.517808  
std        0.815778      1.625393  
min        0.000000      2.000000  
25%        2.000000      5.000000  
50%        3.000000      6.000000  
75%        3.000000      7.000000  
max        8.000000     14.000000

# Decision Tree models
El modelo que vamos a hacer es  scikit-learn, y luego validamos que tal es mediante Mean Absolute Error (also called MAE). Let's break down this metric starting with the last word, error.

The prediction error for each house is: 
error=actual−predicted

In [4]:
from  sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

#Separamos los datos en dos grupos
# split data into training and validation data, for both predictors and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

#1_ Si no cogieramos el training y validación: Hacemos el modelo
melbourne_model= DecisionTreeRegressor()
melbourne_model.fit(X,y)

#Veamos como funciona
print("1_training= test. Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))
print("And the real is")
print(y.head())

val_predicted_home_prices = melbourne_model.predict(X)
print("error para el conjunto de training es: ")
print (mean_absolute_error(y,val_predicted_home_prices ))

#2_ Si cogemos el training y validación: Hacemos el modelo
melbourne_model= DecisionTreeRegressor()
melbourne_model.fit(train_X,train_y)

#Veamos como funciona
print("2_ Training<> Test. Making predictions for the following 5 houses:")
print(val_X.head())
print("The predictions are")
print(melbourne_model.predict(val_X.head()))
print("And the real is")
print(val_y.head())

#Error cometido en esta medicion MAE
print("error para el conjunto de training es: ") 
val_predicted_home_prices = melbourne_model.predict(val_X)
print("error es: ")
print (mean_absolute_error(val_y,val_predicted_home_prices ))

1_training= test. Making predictions for the following 5 houses:
   LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
0     8450       2003       856       854         2             3   
1     9600       1976      1262         0         2             3   
2    11250       2001       920       866         2             3   
3     9550       1915       961       756         1             3   
4    14260       2000      1145      1053         2             4   

   TotRmsAbvGrd  
0             8  
1             6  
2             6  
3             7  
4             9  
The predictions are
[ 208500.  181500.  223500.  140000.  250000.]
And the real is
0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64
error para el conjunto de training es: 
62.3543378995
2_ Training<> Test. Making predictions for the following 5 houses:
     LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
529    32668       1957      2515         0    

In [5]:
# 3_ Ahora vamos a ajustar mejor el modelo definiendo cuantas ramas tendrá el arbol

def get_mae(max_leaf_nodes, predictors_train, predictors_val, targ_train, targ_val):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(predictors_train, targ_train)
    preds_val = model.predict(predictors_val)
    mae = mean_absolute_error(targ_val, preds_val)
    return(mae)

# compare MAE with differing values of max_leaf_nodes
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  35190
Max leaf nodes: 50  		 Mean Absolute Error:  27825
Max leaf nodes: 500  		 Mean Absolute Error:  32662
Max leaf nodes: 5000  		 Mean Absolute Error:  33382


# Random Forest model
The random forest uses many trees, and it makes a prediction by average the predictions of each component tree. It generally has much better predictive accuracy than a single decision tree and it works well with default parameters. If you keep modeling, you can learn more models with even better performance, but many of those are sensitive to getting the right parameters


In [6]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

forest_model = RandomForestRegressor()
forest_model.fit(train_X, train_y)
melb_preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, melb_preds))

23781.467032


# Seleccionar variables


In [79]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

#1) Limpiar datos, borrando valores perdidos

from sklearn.cross_validation import cross_val_score

melb_data= melbourne_data
melb_target = melbourne_data.SalePrice
melb_predictors = melbourne_data.drop(['SalePrice'], axis=1)

# For the sake of keeping the example simple, we'll use only numeric predictors. 
melb_numeric_predictors = melb_predictors.select_dtypes(exclude=['object'])



#funcion para calcular MAE
X_train, X_test, y_train, y_test = train_test_split(melb_numeric_predictors, 
                                                    melb_target,
                                                    test_size=0.3, 
                                                    random_state=0)

def score_dataset(X_train, X_test, y_train, y_test):
    model = RandomForestRegressor(n_estimators=60, max_depth=10, min_samples_split=10, random_state=29011982)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    return mean_absolute_error(y_test, preds)



cols_with_missing = [col for col in X_train.columns 
                                 if X_train[col].isnull().any()]
reduced_X_train = X_train.drop(cols_with_missing, axis=1)
reduced_X_test  = X_test.drop(cols_with_missing, axis=1)

print (cols_with_missing)
print("Mean Absolute Error from dropping columns with Missing Values:")
print(score_dataset(reduced_X_train, reduced_X_test, y_train, y_test))

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']
Mean Absolute Error from dropping columns with Missing Values:
18055.5090564


In [12]:
reduced_X_train.columns

Index(['Id', 'MSSubClass', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea',
       'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr',
       'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars',
       'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold'],
      dtype='object')

In [82]:
#2) Imputation

from sklearn.preprocessing import Imputer

my_imputer = Imputer()
imputed_X_train = my_imputer.fit_transform(X_train)
imputed_X_test = my_imputer.transform(X_test)

#print(pd.DataFrame(imputed_X_train).sample (5))
print("Mean Absolute Error from Imputation:")
print(score_dataset(imputed_X_train, imputed_X_test, y_train, y_test))

Mean Absolute Error from Imputation:
17785.7748086


In [20]:
type(X_train), type(imputed_X_train)  # como son tipos distintos no aplican las mismas propiedades

(pandas.core.frame.DataFrame, numpy.ndarray)

In [83]:
imputed_X_train_plus = X_train.copy()
imputed_X_test_plus = X_test.copy()

cols_with_missing = (col for col in X_train.columns 
                                 if X_train[col].isnull().any())
for col in cols_with_missing:
    imputed_X_train_plus[col + '_was_missing'] = imputed_X_train_plus[col].isnull()
    imputed_X_test_plus[col + '_was_missing'] = imputed_X_test_plus[col].isnull()

# Imputation
my_imputer = Imputer()
imputed_X_train_plus = my_imputer.fit_transform(imputed_X_train_plus)
imputed_X_test_plus = my_imputer.transform(imputed_X_test_plus)

print("Mean Absolute Error from Imputation while Track What Was Imputed:")
print(score_dataset(imputed_X_train_plus, imputed_X_test_plus, y_train, y_test))

Mean Absolute Error from Imputation while Track What Was Imputed:
17804.8957325


In [40]:
# ¿el modelo es estable? hago el cross-validation para un random forest y para un boosting

from sklearn.model_selection import cross_validate

def score_dataset_cv(X_train, X_test, y_train, y_test):
    model = RandomForestRegressor()
    scores = cross_validate(model, X_train, y_train,
                         scoring=('r2', 'neg_mean_absolute_error'))
    print(-scores['test_neg_mean_absolute_error'])      
    print(scores['test_r2'])                         


In [41]:
score_dataset_cv(reduced_X_train, reduced_X_test, y_train, y_test)

[ 20037.52170088  21254.58768328  18538.27235294]
[ 0.80786494  0.85106733  0.84485583]


In [72]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_validate

def score_dataset_cv(X_train, X_test, y_train, y_test):
    model = GradientBoostingRegressor()
    scores = cross_validate(model, X_train, y_train,
                         scoring=('r2', 'neg_mean_absolute_error'))
    print(-scores['test_neg_mean_absolute_error'])      
    print(scores['test_r2'])                         

score_dataset_cv(reduced_X_train, reduced_X_test, y_train, y_test)

[ 17838.61492361  18723.1462148   15069.57012214]
[ 0.79428757  0.8755134   0.89312167]


In [70]:
# hiperparámetros: mirar que parámetros son los que debo cambiar para mi modelo

from sklearn.model_selection import GridSearchCV

parameters = {'n_estimators': [70, 100, 120], 'max_depth': [3, 5, 7, 10], 'subsample': [0.60, 0.7, 0.80],'min_weight_fraction_leaf':[0.20, 0.1, 0.05]}
gbr = GradientBoostingRegressor()
clf = GridSearchCV(gbr, parameters)
clf.fit(reduced_X_train, y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [70, 100, 120], 'max_depth': [3, 5, 7, 10], 'subsample': [0.6, 0.7, 0.8], 'min_weight_fraction_leaf': [0.2, 0.1, 0.05]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [71]:
clf.cv_results_

{'mean_fit_time': array([ 0.11714339,  0.11063226,  0.12684703,  0.1728754 ,  0.17218852,
         0.16924175,  0.17997193,  0.18668445,  0.18607386,  0.12267931,
         0.13055062,  0.13252672,  0.17671243,  0.17018708,  0.16864181,
         0.21145304,  0.20427322,  0.21248802,  0.15325721,  0.15230163,
         0.12965608,  0.19285822,  0.18939575,  0.17586199,  0.22160554,
         0.21080907,  0.20912997,  0.10416691,  0.12761633,  0.12933501,
         0.1494631 ,  0.14823429,  0.15870674,  0.1798652 ,  0.18544054,
         0.18467911,  0.1501797 ,  0.1607914 ,  0.17250355,  0.21540658,
         0.24059312,  0.2426095 ,  0.27144027,  0.26941133,  0.28824711,
         0.18110792,  0.18133903,  0.18775423,  0.24791773,  0.26486731,
         0.28458309,  0.29874619,  0.3225166 ,  0.33392493,  0.11015924,
         0.10737125,  0.11646843,  0.15099899,  0.15411075,  0.16042129,
         0.17211509,  0.17684865,  0.19291862,  0.16465108,  0.16844392,
         0.17785048,  0.22965948, 

In [66]:
clf.best_estimator_

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=5, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.1,
             n_estimators=100, presort='auto', random_state=None,
             subsample=0.7, verbose=0, warm_start=False)

In [84]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_validate

def score_dataset_cv(X_train, X_test, y_train, y_test):
    model = GradientBoostingRegressor(n_estimators= 100, max_depth=5, subsample= 0.7
                                      ,min_weight_fraction_leaf=0.1)
    scores = cross_validate(model, X_train, y_train,
                         scoring=('r2', 'neg_mean_absolute_error'), cv=10)
    print(-scores['test_neg_mean_absolute_error'])      
    print(scores['test_r2'])                         

score_dataset_cv(reduced_X_train, reduced_X_test, y_train, y_test)

[ 17198.96120694  23195.83272626  21463.95294502  20761.49425872
  20182.72379423  22025.80395473  18995.875571    18174.82013286
  15579.48662801  16773.60645665]
[ 0.86531833  0.77064438  0.79723221  0.90047097  0.83797817  0.7653455
  0.85238884  0.84791002  0.90572437  0.86144469]
